### ISSUE TITLE
ToDoList

### ISSUE THREAD

**Issue by skorotkikh** [DataAccess2020/CE2_Korotkikh_Maletskii#1]
1. Download the page using rcurl: https://beppegrillo.it/un-mare-di-plastica-ci-sommergera/
2. Create a data frame with the links on the page
3. Keep the links that lead to other posts of the blog
4. Create the code for pages scraping: https://beppegrillo.it/category/archivio/2016/
5. Get links for each page and put them into a list
6. Download the page for each page (remember to Sys.sleep())
7. Scrape the text for each page
8. Sketch and explain the spider scraper

**Comment by Vadim-Maletskii** [comment]
Everything's done
