### ISSUE TITLE
Don't know how to reveal identity

### ISSUE THREAD

**Issue by skorotkikh** [DataAccess2020/CE2_Korotkikh_Maletskii#3]
Hi @Vadim-Maletskii I found the command rcurl::getURL() thanks to which I can download the page, but I have not found the arguments in the function which could help us reveal our identity to be polite. For example, in httr::GET() we can write our email and user-agent, but in getURL() I have not found such an opportunity. Could you please check how we can do this?

**Comment by Vadim-Maletskii** [comment]
I tried to solve it, look at pull requests

**Comment by skorotkikh** [comment]
@Vadim-Maletskii yes, it is working, thank you! Accepting the request now
